### ISSUE TITLE
首頁顯示熱門詞條

### ISSUE THREAD

**Issue by thewayiam** [g0v/itaigi#106]
剛進去空空的會有點不知道怎麼開始，所以想加個熱門搜尋讓使用者可以直接用點的
目前想到作法：
1. 裝 google analytics，定期去抓本周熱門、本月熱門詞條
2. 用現有的按呢講好，比較多人投過票的前5個詞條

**Comment by sih4sing5hong5** [comment]
1. google analytics 有了，權限可能要麻煩 @pm5 開了
不過用GA比較好維護，還是給後端會比較好維護？

2. 這樣的話要記錄投票的時間嗎？
不然總是那幾個詞佔前面

**Comment by thewayiam** [comment]
恩那還是用GA做好了，投票紀錄時間有點太多餘了

**Comment by liz462** [comment]
有可能抓粉專顯示的詞條嗎？有打算跟著每天的時事上詞。不過這樣管理壓力比較大，直接抓熱門詞是比較方便。

**Comment by sih4sing5hong5** [comment]
GA敢有法度自動化？

粉專的變化較大，可能較趣味？
毋閣抑是愛看liz彼爿有方便無

**Comment by thewayiam** [comment]
> google analytics 有了，權限可能要麻煩 @pm5 開了
> 不過用GA比較好維護，還是給後端會比較好維護？

後端要維護的話怕會影響到以後的效能調整（怕本來可以直接進快取讀取的東西，卻為了這個功能要存取db）；GA可能實作稍麻煩一點，不過我們可以設定每天去 GA 抓一次熱門詞條回來，前端還是讀取 django api，server loading 會比較輕鬆。

我自己理（亂）想的首頁是搜尋框&下方熱門詞條、下方 FB 粉專圖片和影音、最下方聊天區，這樣就都有了

**Comment by sih4sing5hong5** [comment]
主要是咱好維護
liz彼爿負擔莫想大

毋過咱會當閣確定熱門詞條的用途，除了`首頁空空`以外，閣有啥物效果
佮粉專的用途有啥無仝
若咱先確定好，寫起來，以後較袂袂記得閣改來改去

**Comment by sih4sing5hong5** [comment]
#275 做好矣
