### ISSUE TITLE
詞條接臉書討論

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#11]
愛華語詞條接，抑是母語詞條接？

**Comment by pm5** [comment]
假使用母語詞條接，就要有獨立的母語詞條頁比較好。我先來加一個母語詞條頁。

**Comment by sih4sing5hong5** [comment]
母語詞條需要獨立出來一頁嗎？

我原本的意思是
```
華語：漂亮
媠 suí
美麗 bí-lē
```
FB討論區是應該針對`漂亮`，還是`媠`和`美麗`

**Comment by sih4sing5hong5** [comment]
```
Liz Lin
理論上每一個華語詞都會連接到一個以上的臺語詞
Liz Lin
所以是以臺語詞為討論對象
```

**Comment by sih4sing5hong5** [comment]
https://developers.facebook.com/docs/plugins/comments#configurator

**Comment by sih4sing5hong5** [comment]
親像 <http://udn.com/news/story/7240/1633063-%E4%B8%89%E6%98%9F%E5%82%B3%E6%98%8E%E5%B9%B4%E4%BE%9B%E8%98%8B%E6%9E%9COLED%E9%9D%A2%E6%9D%BF>

**Comment by liz462** [comment]
點選"討論"之後，展開翻譯成這個台語詞彙的討論串，形式像樓上列的那樣

**Comment by thewayiam** [comment]
使用 disqus，為了簡化使用介面，目前詞條部分討論以華語為單位
