### ISSUE TITLE
匯入台華辭典

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#110]
匯入
```
Taihoa楊允言老師提供資料庫-推薦用字表外字.csv
Taihoa楊允言老師提供資料庫-漢字.csv
Taihoa楊允言老師提供資料庫-漢羅混合.csv
```

1. `漢羅混合`敢有按算共`漢羅`改做`全漢`？
  1. 匯入去才用sheet改
  2. 先改好才閣匯入
2. 若有佮`教育部辭典`仝款的詞條欲按怎處理？
  1. 程式匯入的時陣檢查，仝款就莫匯
  2. 全部匯入去，有拄著才閣講

**Comment by liz462** [comment]
1.應該是先改較好。
2.上好是檢查，有仝款就莫匯。而且我感覺未來一定會出現資料重複的，可能需要有功能是共重複的刣掉。嘛會使佇「使用者錯誤回報」處理，拄著才隨个去刣。毋過，愛按怎刣？是毋是愛恁佇資料庫內底刣？

**Comment by sih4sing5hong5** [comment]
先用`Taihoa楊允言老師提供資料庫-漢字.csv`
