### ISSUE TITLE
已有資料再"做伙添"之後，無法進到正規化工作表

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#114]
如果沒有資料，使用者貢獻，可以順利進到正規化資料表

如果已有資料，使用者在"閣會使按呢講，我來做伙添”增加資料，則不會進到正規化工作表!!

**Comment by thewayiam** [comment]
@liz462 : 你應該都是在FB已登入的狀況下，點選 `送出` 對吧，不是在`匿名送出`、`登入 & 送出`按的，我理解對嗎？另外要麻煩你提供是在哪個詞下加了什麼

@sih4sing5hong5 : 我在 local 測試是OK的（匿名送出 & 送出），可能要看一下 liz 提供的詞找一下 log

**Comment by sih4sing5hong5** [comment]
我明天晚上才方便看，liz的詞是哪個?

**Comment by thewayiam** [comment]
from liz:
我出門了不方便登入github，那個詞是巨蛋，因為有其他人試用，告訴我他增加了兩個說法，但我在資料表沒看到，我自己也去加詞，發現確實如此
也沒有出現 會幫你改成正字的警語

**Comment by sih4sing5hong5** [comment]
是後端的問題，`"種類和外語不一樣"` 我這馬來修

**Comment by sih4sing5hong5** [comment]
線上機後端換矣
@liz462 閣試看覓呀

**Comment by sih4sing5hong5** [comment]
liz講會使矣

**Comment by sih4sing5hong5** [comment]
liz講會使矣
