### ISSUE TITLE
好工具的內容

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#128]
**字辭典類**
萌典 https://www.moedict.tw/'%E7%99%BC%E7%A9%8E 
教育部《臺灣閩南語常用詞辭典》  http://twblg.dict.edu.tw/ 
台文/華文線頂辭典 http://210.240.194.97/ungian/soannteng/chil/Taihoa.asp
臺日大辭典 http://minhakka.ling.sinica.edu.tw/taijittian/  or  http://taigi.fhl.net/dict/
廈門音新字典(甘字典)  http://taigi.fhl.net/dick/

**輸入法類**
教育部臺灣閩南語漢字輸入法 http://depart.moe.edu.tw/ed2400/cp.aspx?n=BB47AA61331DDAC8&s=5900082022C17E11
信望愛台語客語輸入法  http://taigi.fhl.net/TaigiIME/ 
臺語輸入法(Android)  https://play.google.com/store/apps/details?id=fr.magistry.taigime&hl=zh_TW
羅漢跤台語輸入法(iOS) https://itunes.apple.com/tw/app/lohanka-tai-yu-shu-ru-fa/id1080190324?mt=8

**學習類**
臺灣閩南語推薦用字700字詞  http://ws.moe.edu.tw/001/Upload/userfiles/file/iongji/700iongji_1031222.pdf
臺灣閩南語羅馬字拼音教學網 http://tailo.moe.edu.tw/

**Comment by liz462** [comment]
歡迎補充

**Comment by thewayiam** [comment]
liz 的這篇文章對我這種不懂得很有幫助
http://liztaigi.blogspot.tw/2015/08/blog-post_31.html

**Comment by glll4678** [comment]
**字辭典類**
台華對應綜合大辭典 http://taigi.fhl.net/dic_un/ （同 台文/華文線頂辭典）

**學習類**
臺灣閩南語羅馬拼音及其發音學習網 http://www.ntcu.edu.tw/tailo/
咱來學臺灣閩南語 http://language.moe.gov.tw/files/people_files/資源手冊專頁.pdf

**Comment by sih4sing5hong5** [comment]
@thewayiam 你講的彼篇文直接加入去吧？

我感覺會當攏先加加入去
到時有閒才閣用ga分析愛按怎調整
