### ISSUE TITLE
Safari 上沒有 getUserMedia/Stream API 導致 TypeError

### ISSUE THREAD

**Issue by imkojima** [g0v/itaigi#143]
路過看了一下目前錄音功能尚未使用  #126 

但是在 [/src/GuanKiann/LokIm/LokIm.jsx#L28-L31](https://github.com/g0v/itaigi/blob/2e5de6635294901c9fe495e18d5f3384c2d7dba2/src/GuanKiann/LokIm/LokIm.jsx#L28-L31) 仍會使用到

雖然有吐 rendering 資訊，但由於出現 TypeError 就中止了吧，頁面上看不見結果

Can I use getUserMedia/Stream API? http://caniuse.com/#feat=stream

tested on Safari 10.0（12602.1.40.4）

p.s. 不過這問題目前在 Safari Technology Preview 最新的版本已經解決了（支援webkitGetUserMedia）

**Comment by sih4sing5hong5** [comment]
那麼不要import`LokIm`就可以正常顯示嗎？

**Comment by sih4sing5hong5** [comment]
我在 #145 改了，可以麻煩你用safari看 <http://tshi3.itaigi.tw> 這樣有正常嗎？

**Comment by imkojima** [comment]
可能沒有拉成功，因為 http://tshi3.itaigi.tw 連 Chrome 都開不起來
不過錯誤都是相同的 `LokIm is not defined`

**Comment by sih4sing5hong5** [comment]
我這邊的chrome開得起來
不過我再重佈署一次
再麻煩試一次 @@

**Comment by imkojima** [comment]
現在都正常囉 XD

**Comment by sih4sing5hong5** [comment]
所以safari嘛好矣喲？
感謝～～

**Comment by imkojima** [comment]
無毋著 👍

**Comment by thewayiam** [comment]
safari 9.1.1 版測試也可以 :+1:
