### ISSUE TITLE
透過 webfont 顯示豆腐字

### ISSUE THREAD

**Issue by glll4678** [g0v/itaigi#144]
https://github.com/audreyt/moedict-webkit/tree/master/fonts

**Comment by sih4sing5hong5** [comment]
你的意思是「若使用者電腦無裝字體，用webfont就會當幫伊顯示」？

**Comment by glll4678** [comment]
是。一寡 Ext-C~E 的字裝置可能無字型通好顯示，用 webfont 共伊顯示。
