### ISSUE TITLE
正規化工作表限定編輯

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#148]
正規化工作表可不可以設定為限定編輯？由我加入可編輯的名單。這樣對系統會有影響嗎？

**Comment by sih4sing5hong5** [comment]
會使呀，內底有一个落落長的是資料庫的數號
彼个留咧就會使矣

**Comment by liz462** [comment]
OK，正規化改鎖權限，可以加入者請給我名單，以老鼠會原則來加入
