### ISSUE TITLE
網站怪怪

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#149]
我這馬用firefox，
網站干焦怪怪的，
熱門詞條會變白色的

**Comment by sih4sing5hong5** [comment]
是前端試驗機的問題，一般使用者袂拄著
愛加入readme

<http://giam7.itaigi.tw/k/%E5%AF%B6%E5%8F%AF%E5%A4%A2>
<http://itaigi.tw/k/%E5%AF%B6%E5%8F%AF%E5%A4%A2>

**Comment by thewayiam** [comment]
為什麼試驗機會變白色的？

**Comment by sih4sing5hong5** [comment]
我的筆電會，毋過厝內的電腦袂，我操作流程是按呢

1. 到正式機的`蛋塔`，<http://itaigi.tw/k/%E8%9B%8B%E5%A1%94>
  * `db.itaigi.tw`的response的header有`Access-Control-Allow-Origin:http://itaigi.tw`
2. 到試驗機的`蛋塔`，<http://giam7.itaigi.tw/k/%E8%9B%8B%E5%A1%94>
  * 連`db.itaigi.tw`，瀏覽器用`1`的cache
  * `db.itaigi.tw`的response的header煞是舊的`Access-Control-Allow-Origin:http://itaigi.tw`

所以試驗機就無法度看
若是先看試驗機的`蛋塔`，正式機嘛會出問題

**Comment by sih4sing5hong5** [comment]
這馬無拄著，先關起來
