### ISSUE TITLE
臺語詞目的來源顯示毋著人

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#150]
這馬臺語詞條，下跤的`來源`顯示的是`編輯者`
照理講應該顯示`貢獻者`
抑是兩个攏顯示？

**Comment by liz462** [comment]
貢獻者才著!!!!!  囧囧囧囧囧
死矣按呢毋就足濟條是我囧囧囧

**Comment by thewayiam** [comment]
要不要兩個都放都叫貢獻者，二次確認的放後面
e.g. 貢獻者：johnny、liz

**Comment by liz462** [comment]
我是覺得校對者不用放，未來可以做一個製作團隊名單，那裏再放就好了，畢竟性質不同

**Comment by sih4sing5hong5** [comment]
我明仔載來修做`貢獻者`
