### ISSUE TITLE
網站整體文案愛華語抑是臺語

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#158]
[FB的回饋](https://www.facebook.com/TajfunInsulo/posts/1064334400269369?comment_id=1064669683569174&comment_tracking=%7B%22tn%22%3A%22R0%22%7D&pnref=story)
`還有這個網站一下子用中文一下子用台語，不一致很奇怪。`

1. 全華語
2. 全臺語
3. 維持這馬按呢

**Comment by liz462** [comment]
其實目前是全華語的。
可是，正常雙語環境本來就應該要雙語並存啊......

**Comment by sih4sing5hong5** [comment]
應該是指標題吧
`面冊`、`閣會使按呢講，我來做伙添`

我是感覺按呢就好
偷渡一寡仔臺語文 XDD

**Comment by thewayiam** [comment]
我也覺得不用統一，像`做伙添`，如果他要添他應該是看得懂台語漢字了，但`台語怎麼講`要使用的人是可能看不懂的，就不太應該寫台語漢字

**Comment by sih4sing5hong5** [comment]
逐家攏認為莫改，

issue足濟，感覺就煩的，共因關關掉！！
