### ISSUE TITLE
送出新詞時，愛顯示"台語阿肥會先幫忙改成正規用字再送出喔"

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#16]
在`ABo`的`加外語新詞文本`函式
81行的`then`（`.then(({body}) => (console.log('sui2')))`）改成
顯示`台語阿肥會先幫忙改成正規用字再送出喔`

**Comment by sih4sing5hong5** [comment]
愛用啥物套件？效果是？

**Comment by liz462** [comment]
https://www.facebook.com/1personand2cats/photos/a.1682559675298440.1073741828.1682556988632042/1683716928516048/?type=3&permPage=1 
台語阿肥(右邊那隻)

**Comment by pm5** [comment]
改成正規用字，是會有編輯去檢查修正用字，才會送進資料庫裡，是這樣吧？那應該要做成照常 post，在 then 裡面檢查如果 post 成功，就浮一個對話框出來說明這樣。

**Comment by pm5** [comment]
加了 react-modal，可以用來做對話框。照著[文件](http://react-components.com/component/react-modal)做應該就可以了。

**Comment by sih4sing5hong5** [comment]
現在是用`alert`，要改成用`react-modal`
`.then(({ body }) => (alert('台語阿肥會先幫忙改成正規用字再送出喔')))`

**Comment by sih4sing5hong5** [comment]
套件網址：https://github.com/rackt/react-modal

**Comment by liz462** [comment]
已經做出來了，可是跑出視窗的速度很慢??ㄥ
