### ISSUE TITLE
簽名都不見了，找不到規則

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#160]
https://g0v-tw.slack.com/archives/itaigi/p1469455803000178

**Comment by sih4sing5hong5** [comment]
#138 修好矣

**Comment by thewayiam** [comment]
https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/pull/138

**Comment by sih4sing5hong5** [comment]
指錯人了 XD
