### ISSUE TITLE
關於本站加製作團隊

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#161]
對 https://github.com/g0v/itaigi/issues/134#issuecomment-234711896 分出來

**Comment by liz462** [comment]
製作團隊真的可以放一下，把勞苦功高的各位名字列出來之外，也是一種資源共享的概念XD  或者未來寫履歷時可以當作證明這樣

**Comment by aweimeow** [comment]
今天翻到這個 issue XD 頂起來一下
所以說貢獻者 / 製作團隊 兩個會分開放嗎？
貢獻者會像 "好工具" 這樣子獨立起來成一頁嗎

**Comment by liz462** [comment]
我初步的想法是：
「關於本站+製作團隊」一個頁面
「使用方法」一個頁面
「貢獻者」(就是原本說的"名人堂")一個頁面，包括詞彙貢獻者和正規化團隊，呈現方式放在名人堂那個issue

(10/1的萌典松有好多工作要做@@)

**Comment by a8568730** [comment]
攻城獅的github個人首頁，就是很好的履歷囉～
人員來來去去的，列或不列都很不好意思。
