### ISSUE TITLE
要怎麼管理沒正規化的詞條

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#163]
原本佇 #107 想講共簽名提掉，較好揣
毋過會發生 #160 的問題
所以就佇 https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/pull/138 提掉這个功能

看是程式匯入資料庫的時陣，發覺詞條怪怪，愛按怎處理
1. email通知正規化團隊
2. 做記號佇簽名後壁的欄位

**Comment by liz462** [comment]
做記號較好。

**Comment by liz462** [comment]
還有現在「我很會」裡面有些東西也要清掉
