### ISSUE TITLE
做名人堂

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#164]
這馬線上矣
`名人堂`暫時佇 #124 提掉

`名人堂`應該愛先做，獎勵正規化團隊

預計用一个資料庫table，記人名佮筆數
閣開一个api，予前端掠

除了照`全部正規化數量`排以外
敢閣愛一位是`這禮拜/這個月正規化上濟的人`，鼓勵新人鬥相共

**Comment by liz462** [comment]
我傾向「我很會」提供講法囥佇名人堂
正規化團隊我愛閣觀察一下，目前有幾若款狀況，我無講真確定欲遐鼓勵XD
若真正欲做會當參考這：
http://taigisukhoo.tw/BingJinTong.html
(死去的坑.....)

**Comment by sih4sing5hong5** [comment]
若是正規化的人傷濟，會當偷偷仔下台華辭典予in正規化 （誤）

你若想好，阮這爿就會開始做

**Comment by liz462** [comment]
允言老師資料庫用字無問題的先匯入去較實在XD
用字有問題的進前有請逐家鬥看毋過無啥成果：
https://docs.google.com/spreadsheets/d/1K_bsnk31w0pw1nQK21aWJVy_jYK8Q_3Sf7woyZ2cBiw/edit?usp=sharing

才看會當按怎利用。

我今嘛猶毋敢揣傷濟正規化團隊的人，想講紡一陣仔，看有啥問題無。

**Comment by liz462** [comment]
貢獻者會想欲看著家己的貢獻，目前貢獻講法的人無啥有夠，應該會當做貢獻者的名人堂～～

**Comment by sih4sing5hong5** [comment]
猶未正規化出來的，先莫算？
  * 若是猶未正規化出來的愛算，重覆的、來亂的會歹處理

**Comment by aweimeow** [comment]
我等等要把這個功能丟到測試機 itaigi-test 囉！
然後晚點會送 PR，請有空的大家幫我看看我改的 code 有沒有問題 XD 對前端不太熟，

再來就是尚未解決的排名問題，有人對於把數量變成小圖示有任何想法或是任何想用的圖示嗎？
