### ISSUE TITLE
DISQUS 討論的詞條整併問題

### ISSUE THREAD

**Issue by aweimeow** [g0v/itaigi#168]
以「天燈」一詞為例，
在 怎麼講 - 天燈 [http://itaigi.tw/k/天燈](http://itaigi.tw/k/天燈)
與 我很會 - 天燈 [http://itaigi.tw/t/天燈](http://itaigi.tw/t/天燈)
兩者的 DISQUS 討論是不同的，

一個的討論是連結到 `/k/天燈` ，而另一個則是 `/t/天燈`，
如果可以的話，我認為可以合併在一起，畢竟都是同一個詞條，

不過合併會有一個[明顯的問題](https://g0v-tw.slack.com/archives/itaigi/p1469534229000253)：
【如果沒有既定講法之前，針對可能講法的討論放在同一塊會比較簡潔】

但是如果能夠開發一個新功能，
可以針對 `講法` tag 的話，把討論者的留言以 tag 分開，
那這樣子就能夠避免前述問題，讓討論區的留言能夠以簡潔的方式分隔開來。

**Comment by sih4sing5hong5** [comment]
我感覺

* `怎麼講 - 天燈 http://itaigi.tw/k/天燈`佮`我很會 - 天燈 http://itaigi.tw/t/天燈`用仝一條disqus
* `我很會 http://itaigi.tw/t` 莫下disqus

就無濫做伙的問題矣
