### ISSUE TITLE
提供講法，臺羅的欄位預設敢著藏起來

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#169]
https://g0v-tw.slack.com/archives/itaigi/p1469534524000271

使用者會當分兩種

1. 會曉臺羅，提供講法時會鬥拍臺羅
2. 袂曉臺羅佮教育部漢字，照華語的慣勢拍

若有`臺羅`欄位，驚會驚著第`2`種使用者
若無`臺羅`欄位，第`1`種使用者無方法

目前有`臺羅`欄位，正規化表393筆有273筆有提供`臺羅`
欲按怎設計，會當顧著第`2`種使用者？

**Comment by aweimeow** [comment]
如果在：我會曉，「＿＿」會使按呢講 的這個時候，
下面出現的不是兩個欄位而是兩個按鈕，
* 我會曉臺羅
* 我不會臺羅

這樣子把使用者劃分成兩類，提供不同的方式來新增詞條的念法，
* 我會曉臺羅 -> 提供原本的欄位
* 我不會臺羅 -> 提供錄音或是讓使用者以自己會的方式作表達（用上漢字、注音符號、英文字母）

不知道能不能夠解決問題

**Comment by sih4sing5hong5** [comment]
不錯耶
然後再用cookie記他的選擇
就不用選第二次了
頂多旁邊再換一個切換功能

**Comment by liz462** [comment]
我覺得不用，首先會台羅的也不一定都對，再者打台羅對正規化團隊來說並不困難。
至於使用者，我們反而應該是鼓勵使用者不要怕盡量寫，在PTT上也沒人怕寫火星文啊XD
當然長遠來說是鼓勵大家學台羅~~
（好像應該在萌典松短講教台囉?）
