### ISSUE TITLE
小屁孩 有資料，煞出現佇「我很會」

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#173]
liz 講的 https://g0v-tw.slack.com/archives/itaigi/p1469630149000321

![default](https://cloud.githubusercontent.com/assets/5996555/17198175/d2c084d8-54a5-11e6-95d6-a5a0488e5ce6.png)
![default](https://cloud.githubusercontent.com/assets/5996555/17198186/e557180a-54a5-11e6-90ae-db8b4d31c8a5.png)

**Comment by sih4sing5hong5** [comment]
看資料庫
佇`我很會`的是編號`47916`的`'小屁孩 '`
佇`怎樣講`的是編號`47974`的`'小屁孩'`

**Comment by aweimeow** [comment]
感覺是使用者輸入的資料要做過處理再丟進資料庫（？）
```py
'小屁孩 '.strip()
```

**Comment by sih4sing5hong5** [comment]
@aweimeow 這個可以麻煩你改嗎？
我有先加試驗了
就從 https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/pull/140 的`資料入資料庫前愛strip` branch改就行了

**Comment by sih4sing5hong5** [comment]
你現在跑`python manage.py test`應該會有`FAILED (failures=2)`

**Comment by aweimeow** [comment]
@sih4sing5hong5 
好 :+1:

**Comment by sih4sing5hong5** [comment]
之後 #91 的功能可能也要配合先做

**Comment by liz462** [comment]
又發現一個，棉花棒，也是一樣的情況

**Comment by sih4sing5hong5** [comment]
#91 做好後，我再一口氣拿掉

**Comment by sih4sing5hong5** [comment]
這以早就做好矣
