### ISSUE TITLE
iTaigi 愛台語網站的 icon 沒有放

### ISSUE THREAD

**Issue by aweimeow** [g0v/itaigi#174]
```html
<link rel="icon" href="icon_location">
```

不懂前端 XD 不過應該是這樣子寫，看了網頁的 source 發現沒有放 icon

**Comment by sih4sing5hong5** [comment]
直接轉，圖不好看
而且好像要正方形的
![favicon](https://cloud.githubusercontent.com/assets/5996555/17208028/a7152188-54e9-11e6-826e-673b9a22a067.png)

**Comment by aweimeow** [comment]
可能需要重新改 LOGO 了 XD
切成正方形是這樣 ![](http://i.imgur.com/AFPz8sP.png)

**Comment by sih4sing5hong5** [comment]
favicon好多規範 @@
我先用在 http://giam7.itaigi.tw/  

@aweimeow 你看得到嗎？


一堆規範：

* http://realfavicongenerator.net/favicon_checker#.V5n_Je2fFyQ
* http://realfavicongenerator.net/faq#why_so_many_files
* http://stackoverflow.com/questions/4014823/does-a-favicon-have-to-be-32x32-or-16x16

**Comment by aweimeow** [comment]
我的 browser 沒有看到耶，
是這一行嗎？
```html
    <meta itemprop="image" content="https://s3-ap-southeast-1.amazonaws.com/itaigi.tw/images/logo.png">
```

**Comment by sih4sing5hong5** [comment]
若檔名號`favicon.ico`就免加meta
我有傳起哩，我嘛看無
毋過 http://realfavicongenerator.net/favicon_checker#.V5n_Je2fFyQ 伊回報會使
可能閣佇cache
我過一陣仔才看好矣
