### ISSUE TITLE
FB分享鍵

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#175]
放在`怎樣講`可以一鍵分享詞條
或是`我很會`可以讓分享問題問朋友

**Comment by aweimeow** [comment]
![](http://i.imgur.com/GObKg3h.png)
感覺可以放在這個位置，再附上一些文字
```
【哇！原來「水母」是這樣子講的！快分享給你的朋友知道吧 [按鈕] [按鈕] [按鈕] [按鈕]】
【真是太難想像了，「水母」居然是這樣子說！考考你的朋友吧 [按鈕] [按鈕] [按鈕] [按鈕]】
```

至於為甚麼會放那麼多個按鈕 ... XD
因為社群媒體有好多個，所以想說可以多做幾種不同的，
常見的就有：Facebook, Google Plus, Plurk, Twitter, ... 更甚至是 Line

或者是點一下可以跳出一個小窗讓使用者複製，
內容就跟前面大致一樣，不過是：
```
嘿嘿，讓我來考考你吧！
「水母」的台語要怎麼說呢？

iTaigi 愛台語 - 你的專屬台語辭典
```
這之類的文宣（？）

寫一下自己的想法 ... 沒想到寫著寫著就寫這麼多字了 XD

**Comment by sih4sing5hong5** [comment]
文案好強哦
看了覺得好想用！！

**Comment by liz462** [comment]
嘿嘿，讓我來考考你吧！
「水母」的台語要怎麼說呢？

這個好耶！超讚！  

"太難想像了"可能會遇到並不會很難想像的詞XD

**Comment by sih4sing5hong5** [comment]
#171 現在是預設`大家來學台語，大家做伙來豐富台語`
這个敢愛想別的？

![default](https://cloud.githubusercontent.com/assets/5996555/17235573/b8db7422-5574-11e6-8eb0-9e5922ac3284.png)

**Comment by aweimeow** [comment]
我覺得應該暫時放這個就可以了，之後要改再改也很容易 :smiley:

**Comment by sih4sing5hong5** [comment]
在「我很會」分享，連結是不是要連去「怎麼講」？

**Comment by sih4sing5hong5** [comment]
```
嘿嘿，讓我來考考你吧！
「水母」的台語要怎麼說呢？
``` 
這愛下佗位？

**Comment by aweimeow** [comment]
@sih4sing5hong5 
這個有沒有辦法根據分享不同的詞條顯示不同的字呢？
如果可以的話，我覺得首頁就跟原本一樣，
其他詞條就把 `大家來學台語，大家做伙來豐富台語` 改成那個，
這樣子或許看起來會比較好

**Comment by sih4sing5hong5** [comment]
會使，我來做～～

**Comment by sih4sing5hong5** [comment]
我感覺`你的專屬台語辭典`這種副標有法度幫助別人知影itaigi
毋過咱敢算`辭典`？

**Comment by aweimeow** [comment]
@sih4sing5hong5 
我覺得可以耶，因為不只正規字典有的詞都會有，
還有一些不常見、甚至新詞都可能在這邊查的到

**Comment by liz462** [comment]
嚴格來說我們目前不能算辭典，台語華語線頂辭典也不能算辭典，不過一般人好像也不會管太嚴格的定義？而我們未來也確實會朝向辭典發展(？)，所以.......(我留言到底為了什麼......)
