### ISSUE TITLE
愛台語可提供Mobile版本?

### ISSUE THREAD

**Issue by ellenpost** [g0v/itaigi#187]
如果在手機上開itaigi  可以讓itagi 的網頁 縮小成適合手機可看的版本畫面嗎?
適用於 ios 和 android.

**Comment by ellenpost** [comment]
需要設計ios and android 的手機網頁配置!!! 可能要拿掉一些元件....

**Comment by liz462** [comment]
有人推坑了，超期待啊！！拜託快做出來~~

**Comment by hankkk** [comment]
#213
