### ISSUE TITLE
FB分享，有時陣無縮圖

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#202]
`http://itaigi.tw/k/%E5%AF%B6%E5%8F%AF%E5%A4%A2`無
`http://itaigi.tw/`有

有可能是因為gh-pages 404的關係

**Comment by hankkk** [comment]
`http://itaigi.tw/k/%E5%AF%B6%E5%8F%AF%E5%A4%A2` 無
`http://tshi3.itaigi.tw/k/%E5%AF%B6%E5%8F%AF%E5%A4%A2` 有
`http://test.itaigi.tw/k/%E5%AF%B6%E5%8F%AF%E5%A4%A2` 有
真奇怪

**Comment by sih4sing5hong5** [comment]
`tshi3`敢是拄仔deploy的？
抑是有branch影響著 @@？

**Comment by hankkk** [comment]
`test` `tshi3` 都是上禮拜deploy的
`giam7` 剛剛看也有圖

跟gh-page server ip有差?
`test` `tshi3` `giam7` 151.101.32.133
`itaigi.tw` 192.30.252.153

**Comment by sih4sing5hong5** [comment]
@hankkk 敢愛重deploy一擺看覓？
@audreyt `itaigi.tw`佮`test.itaigi.tw`敢有無仝？

**Comment by hankkk** [comment]
我看facebook og debugger
`<title>`前面的`<meta charset="utf-8">`有抓到

![2016-08-13 5 13 53](https://cloud.githubusercontent.com/assets/8756959/17642445/29ef5e74-617a-11e6-981a-f868498786f1.png)

要不要把全部`<meta>`搬到`<title>`前面試試看
#208

**Comment by audreyt** [comment]
@sih4sing5hong5 
<img width="903" alt="screen shot 2016-08-13 at 5 40 40" src="https://cloud.githubusercontent.com/assets/20723/17642549/18e3d594-617d-11e6-8c98-03fadb285966.png">

**Comment by hankkk** [comment]
#208 deploy後也無效...

**Comment by sih4sing5hong5** [comment]
@au `itaigi.tw`應該是`CNAME`指去`g0v.github.io` ？

**Comment by audreyt** [comment]
OK, 頂層網域其實不能直接 CNAME，我用 CNAME Flattening 設定了 https://support.cloudflare.com/hc/en-us/articles/200169056-CNAME-Flattening-RFC-compliant-support-for-CNAME-at-the-root

**Comment by sih4sing5hong5** [comment]
新deploy也不行 
http://giam7.itaigi.tw/k/%E5%AF%B6%E5%8F%AF%E5%A4%A2

**Comment by sih4sing5hong5** [comment]
更神了
`http://itaigi.tw/k/%E5%82%91%E5%B0%BC%E9%BE%9C` `傑尼龜`可以
`http://itaigi.tw/k/Squirtle` `Squirtle` 不行

**Comment by sih4sing5hong5** [comment]
`Squirtle` 又可以了
不過`寶可夢` 還是不行

**Comment by hankkk** [comment]
現在應該沒這些問題了吧~?

**Comment by sih4sing5hong5** [comment]
攏改過矣，應該無矣。拄著才閣講
