### ISSUE TITLE
我很會的詞條，改用modal

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#204]
https://github.com/g0v/itaigi/pull/186#issuecomment-238062351

**Comment by sih4sing5hong5** [comment]
若按呢做，「我很會」就無disqus，敢無要緊？

**Comment by sih4sing5hong5** [comment]
會當參考`KiuKongHuat.jsx`佮`SangTshut.jsx`的`import Modal from 'react-modal';`

**Comment by liz462** [comment]
「我很會」就無disqus→我感覺無要緊，無顛倒較好，因為有人直接佇遮講：XXX敢有合。
我請伊直接貢獻.......

**Comment by aweimeow** [comment]
要不要之後來寫一頁新手指南 XDD
可以簡單明瞭的介紹各功能以及如何 contribute！

這樣子的話就可以避免掉想貢獻卻手足無措的情況了 ~

**Comment by liz462** [comment]
其實算有耶XD  只是多數人不會看，這很正常XDDD
http://itaigi.tw/about

**Comment by aweimeow** [comment]
有點想把這個 /about 改版 XD
可是我不擅長刻前端
頂多只能用手畫出想法 QQ

**Comment by sih4sing5hong5** [comment]
其實我舊年閣袂曉reactjs

你若有興趣學，
先去看reactjs的`props`佮`state`有啥無仝
才閣看這
https://github.com/g0v/itaigi/issues/204#issuecomment-239465330

**Comment by sih4sing5hong5** [comment]
#272 愛先處理

**Comment by sih4sing5hong5** [comment]
愛做的代誌
1. 我很會，點出來的詞條下佇modal
2. disqus提掉

**Comment by sih4sing5hong5** [comment]
維持這馬按呢，因為一个華語一擺有可能貢獻兩个
