### ISSUE TITLE
合成語音card無法顯示

### ISSUE THREAD

**Issue by hankkk** [g0v/itaigi#209]
ba4e2e851989a0087cab9676b2f123ef7b11fbbc 在 local development 跑的結果

![2016-08-13 8 50 38](https://cloud.githubusercontent.com/assets/8756959/17643278/ca6671d6-6197-11e6-8566-feeb3b487137.png)
![2016-08-13 8 51 10](https://cloud.githubusercontent.com/assets/8756959/17643279/ca6b313a-6197-11e6-8a3f-8cebcb5ffe5c.png)

**Comment by sih4sing5hong5** [comment]
#206 merge入去就好矣

**Comment by sih4sing5hong5** [comment]
@hankkk 麻煩你merge矣
