### ISSUE TITLE
寶島可夢專門做一頁

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#210]
#207 #125

共全部的`抱去摸`攏列出來

**Comment by ellenpost** [comment]
放一個mockup 網頁版面給大家討論看看
![1pagelayout](https://cloud.githubusercontent.com/assets/7560231/19012477/9b4addf6-87e9-11e6-9ed0-c2fcdd4651e2.png)

**Comment by liz462** [comment]
需要處理：
1.前端呈現設計(包括主題頁面本身，以及放在首頁的連結要怎麼擺)
2.後端怎麼幫目標詞彙做記號、怎麼批次提供這些詞
3.音檔除了原本的語音合成，可能會有別的音檔放進去(請特定人士錄製的)

主題詞在網站查詢時也都查得到，只是抓出來在另外的頁面一起呈現。

**Comment by fhj17** [comment]
![default](https://cloud.githubusercontent.com/assets/20688839/20236122/3a1bfb0c-a8e4-11e6-8a6c-73cac3a0f2a8.png)

**Comment by aweimeow** [comment]
覺得 @fhj17 畫的這個不錯，
但是以使用者的角度來思考，我會比較想知道特定幾種的說法，
所以會需要搜尋框 QQ

**Comment by sih4sing5hong5** [comment]
搜尋框另外一个issue好矣
若這馬無問題就先上線
後擺才閣來改
