### ISSUE TITLE
送往後端的 requests 出現 403 Forbidden

### ISSUE THREAD

**Issue by aweimeow** [g0v/itaigi#214]
POST `平臺項目/加外語`
CSRF verification failed. Request aborted.

**Comment by sih4sing5hong5** [comment]
@audreyt 可以麻煩你看一下`db.itaigi.tw`有沒有設定cache呢？
我`ping db.itaigi.tw`
會跑出`PING db.itaigi.tw (104.27.161.104) 56(84) bytes of data.`

實際主機是`139.162.14.198`
再麻煩你順便看一下 https://github.com/g0v/itaigi/issues/202#issuecomment-239622423
多謝～～

**Comment by sih4sing5hong5** [comment]
我有移掉`gunicorn`來確認有吃到`virtualenv`

**Comment by sih4sing5hong5** [comment]
後端改用`http`就會使矣 
https://github.com/g0v/itaigi/blob/master/src/App/App.jsx#L13

我先自master，改做http，deploy起哩

**Comment by audreyt** [comment]
沒有開 cache，但是原本有開 proxy。我剛把 proxy 關掉了。

**Comment by sih4sing5hong5** [comment]
謝謝，我們再試試是什麼問題

**Comment by sih4sing5hong5** [comment]
@aweimeow 這馬干焦會使矣，
我npm start連https會使

你閣試看覓，所以可能是proxy的問題
若會使，才麻煩你重deploy一擺

你若毋知愛用啥試驗資料
會當用地名，`打狗`佮`打貓`已經予我用去矣 XDD

**Comment by aweimeow** [comment]
好 ~ 我現在試試看！

**Comment by aweimeow** [comment]
現在是可以用的，我等等 deploy 到正式機
![Uploading 2016-08-14_222013.jpg…]()

**Comment by aweimeow** [comment]
完成了 d(`･∀･)b

**Comment by liz462** [comment]
@aweimeow  現在沒聲音和這個有關嗎??

**Comment by aweimeow** [comment]
@liz462 應該是無關的，合成聲音是在另外一台機器，
合成聲音的機器網址：`voice.itaigi.tw`
儲存資料的後端網址：`db.itaigi.tw`

我找看看聲音消失的原因 ~
