### ISSUE TITLE
合聲有問題

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#216]
```
臺灣言語工具.解析整理.解析錯誤.解析錯誤: '詞內底的型「phuè-pī/phè-pī」比音「phuè-pī/phè-pī」濟！5：3'
```
`phuè-pī/phè-pī`愛變`phuè-pī｜phuè-pī 。｜。 phè-pī｜phè-pī`
`。`是為著頭前莫變調

**Comment by sih4sing5hong5** [comment]
造成 https://github.com/g0v/itaigi/issues/214#issuecomment-239678117

**Comment by sih4sing5hong5** [comment]
範例：<http://itaigi.tw/k/%E6%B0%B4%E9%80%86>

**Comment by liz462** [comment]
我這邊遇到的情況是，按第一個發音，會需要等滿久的才有聲音，之後才會恢復正常。可是之前都是即按即有聲。

**Comment by sih4sing5hong5** [comment]
等久的→太久沒人用→所以主機就沒存→現場合成→等較久
揤落隨有聲→拄仔有人捌聽過→主機有存音檔→隨放予你聽

這應該會使調整，予主機存較久咧

**Comment by sih4sing5hong5** [comment]
我另外開一个issue #222
