### ISSUE TITLE
合成主機獨立出來

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#219]
為著處理 #216 這種問題
所以愛共主機扣一份出來

看欲下佇佗一臺vm

**Comment by sih4sing5hong5** [comment]
目前load：`load average: 0.04, 0.08, 0.12`

**Comment by sih4sing5hong5** [comment]
抑是直接整合落後端

**Comment by aweimeow** [comment]
整入後端 +1

**Comment by sih4sing5hong5** [comment]
到時愛觀察為啥物會當掉
因為合成的扣本底是c寫的，我用native接起來的
到時若bug揣無，就愛不三時重開 @@

**Comment by aweimeow** [comment]
扯到網路的東西就變得不好 debug 了 XD

**Comment by sih4sing5hong5** [comment]
扯到C就不好debug了 @@

愛閣整理的django套件：https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_hok8-bu7
兩年無綴咧更新的HTS合成套件：https://github.com/sih4sing5hong5/hts_engine_python

**Comment by sih4sing5hong5** [comment]
我把 `合成` 的文件整理出來矣

https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_hok8-bu7/wiki/%E4%BD%BF%E7%94%A8%E7%AF%84%E4%BE%8B%E6%A8%A1%E5%9E%8B

**Comment by aweimeow** [comment]
辛苦了 ~ ヽ(✿ﾟ▽ﾟ)ノ

**Comment by sih4sing5hong5** [comment]
@aweimeow 麻煩你看覓，範例敢會走？
抑是文件愛先補啥？

**Comment by sih4sing5hong5** [comment]
前端佇遮 https://github.com/g0v/itaigi/blob/master/src/GuanKiann/HuatIm/HapSing.jsx#L46
