### ISSUE TITLE
求講法的其他建議

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#231]
若揣無詞的時陣，
`其他建議`會佇`disqus`下跤
無明顯

因為`查的人`一定比`提供臺語講法`的人濟
所以`其他建議`敢愛下較面頂咧

**Comment by aweimeow** [comment]
+1
然後呈現方式我也認為需要再討論，
For example: 搜尋 `歹勢` 會找到很多念法有歹勢的詞條，
所以我認為比較理想的呈現方式可能是 ...
能夠把這些集合以華文文本分隔開來，
`對不起` 然後一條線，下面是對不起的所有台語唸法（當然包含歹勢）
`抱歉` 然後一條線，下面是抱歉的所有台語唸法（歹勢當然也包含在其中）

上述是舉個例子 ... XD 我沒有去驗證資料庫的對不起及抱歉都有對應到歹勢 XD

**Comment by sih4sing5hong5** [comment]
` 能夠把這些集合以華文文本分隔開來，`
其實這馬就是按呢
只是無共華語顯示出來

![default](https://cloud.githubusercontent.com/assets/5996555/18025251/6eddbefe-6c56-11e6-8de1-de5d9e5f00e7.png)
第一逝華語`訕`
第二三逝一區華語`難為情`

應該愛改前端的`GuaGi`

**Comment by liz462** [comment]
#247
