### ISSUE TITLE
怎樣講頁面下方相關詞排列不整齊

### ISSUE THREAD

**Issue by hankkk** [g0v/itaigi#235]
http://itaigi.tw/k/%E7%85%A9

網頁往下捲到相關的詞，排列不整齊

![2016-09-04 10 59 08](https://cloud.githubusercontent.com/assets/8756959/18228764/ea2c0c9e-728e-11e6-9baa-94a8353c6cf1.png)

**Comment by aweimeow** [comment]
這個是因為後端會找出相關詞 ~ 所以以列為單位來分隔出不同的語詞，
可以參考 #231 這邊所寫的 ~

在這個例子當中，華語在這裡分別是：第一排是心頭煩悶、第二排是心情煩躁、第三排是不厭其煩

**Comment by sih4sing5hong5** [comment]
這个做法逐家攏會誤會

看UI是欲按怎改較好？

**Comment by liz462** [comment]
相關的詞全部依序排列就好，不用依華語的不同分開排

**Comment by sih4sing5hong5** [comment]
@aweimeow 咱愛來改`其他建議`的回傳內容矣

**Comment by hankkk** [comment]
#261 有解
