### ISSUE TITLE
查詞條載入小可慢

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#240]
1. 共`其他建議`拆去第二个ajax
2. （毋知影有效無）共`transmit`改用一般的`ajax`

**Comment by sih4sing5hong5** [comment]
造成 #241 的原因之一

**Comment by aweimeow** [comment]
`1` ++

覺得其他建議可以延遲幾秒，使用者不會這麼快看到 XD

**Comment by sih4sing5hong5** [comment]
`其他建議`應該
* 先拆做另外一个介面
* 愛改做回傳`台語詞條`

因為
* 前端這是照台語輸出 #261
* 速度慢應該是慢佇`'新詞文本': 外語.揣新詞文本()`，用台語就免矣

**Comment by liz462** [comment]
會留頂一改的查詢結果，敢是仝款的問題？

**Comment by aweimeow** [comment]
@liz462 那個是因為伺服器的延遲造成前一秒結果比較慢到，所以前一秒的結果一到就把新的結果刷掉了

應該是這樣子 XD

**Comment by sih4sing5hong5** [comment]
@aweimeow 我這兩工共試驗寫好，到時程式再麻煩你鬥看~~

**Comment by aweimeow** [comment]
好～

**Comment by sih4sing5hong5** [comment]
https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/pull/187 做好矣
查`五`，對10秒變做0.5秒
