### ISSUE TITLE
查詞條會出現錯誤

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#241]
華語`五`較慢
華語`漂亮`較慢

先在搜尋列打`五`，等兩秒，還沒跑出來前，
改打`漂亮`
會先出現`漂亮`
過幾秒後，會出現`五`的資料，`漂亮`會不見

**Comment by aweimeow** [comment]
Race Condition 嗎 ( ?

**Comment by sih4sing5hong5** [comment]
著，家己用ajax做嘛可能有這个問題？

**Comment by sih4sing5hong5** [comment]
#240 的問題處理好勢，這馬設定2秒更新一擺，應該就無問題矣
