### ISSUE TITLE
找不到詞的時候，相關建議太下面

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#247]
親像：[人討厭](http://itaigi.tw/k/人討厭)

![2016-10-01 12 24 11](https://cloud.githubusercontent.com/assets/5996555/19011734/0504a2d0-87d2-11e6-9084-e424ba238c65.png)

**Comment by liz462** [comment]
討論後的決議：

「閣會使按呢講，我來做伙添」改設計成一張卡片，放在所有說法的最後面
「相關的詞」接著出現
最後才是討論功能
