### ISSUE TITLE
FB分享用的縮圖，建議尺寸為1200 x 630

### ISSUE THREAD

**Issue by glll4678** [g0v/itaigi#248]
facebook 最佳比例

**Comment by hankkk** [comment]
好像也要多加 `.tw`

**Comment by a8568730** [comment]
@hankkk 是指這個嗎？
```
<meta property="og:locale" content="en_GB" />
```

**Comment by sih4sing5hong5** [comment]
https://developers.facebook.com/docs/sharing/best-practices
```
4.將圖像最佳化以產生絕佳的預覽
圖像尺寸

請對高解析度裝置使用至少 1200 x 630 像素以獲得最佳顯示。您應該至少使用 600 x 315 像素的圖像來顯示具有更大圖像的連結網頁貼文。圖像大小最大可為 8MB。
小型圖像

如果您的圖像小於 600 x 315 像素，該圖像仍會顯示在連結網頁貼文中，但尺寸會變得更小。

我們已經重新設計連結網頁貼文，如此圖像在桌面版和行動版動態消息上便能夠有相同的長寬比。請嘗試將圖像長寬比盡可能保持為 1.91:1，以便在動態消息顯示未經裁切的完整圖像。
```

**Comment by a8568730** [comment]
![fb_og_old](https://cloud.githubusercontent.com/assets/6355592/23010228/376b0b3e-f455-11e6-95ab-6fc0c6155a83.png)
![itaigi_og_600x315](https://cloud.githubusercontent.com/assets/6355592/23010231/3a2e4430-f455-11e6-8aee-6426bfed6f2d.png)

**Comment by sih4sing5hong5** [comment]
#366 檢查好矣
