### ISSUE TITLE
index.html的bundle

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#254]
因為 #253 ，這馬`index.html`的`bundle.js`是指去正式機
對開發來講無方便

希望無需要改來改去

**Comment by sih4sing5hong5** [comment]
@hankkk 你拜六講bundle.js用redirect會拄著啥物問題？

**Comment by hankkk** [comment]
@sih4sing5hong5 連g0v.github.io/itaigi/bundle.js，會轉去抓itaigi.tw/bundle.js

**Comment by sih4sing5hong5** [comment]
https://github.com/g0v/itaigi/blob/master/package.json#L11 的`(echo 'itaigi.tw' > build/CNAME)`提掉敢有幫助？

**Comment by hankkk** [comment]
提掉CNAME可能有用
設定那邊可能也要調整
https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

**Comment by sih4sing5hong5** [comment]
設定改矣

**Comment by hankkk** [comment]
猶是無效，查 DNS 有 www.itaigi.tw 指到 github
https://who.is/dns/itaigi.tw

請Johnny拿掉試試？
@thewayiam

**Comment by hankkk** [comment]
剛剛看g0v.github.io/itaigi/bundle.js已經不會再轉到itaigi.tw了

**Comment by hankkk** [comment]
#258 
開發用`bundle.js`
正式才用`g0v.github.io/itaigi/bundle.js`

**Comment by sih4sing5hong5** [comment]
#258 的`html/devTemplate`合併到`html/index.html`
予 `試驗機`佮`npm start`用仝一个`index` ?

**Comment by hankkk** [comment]
連`itaigi.tw`會用`html/index.html`
連`itaigi.tw/k/...`才用`prodTemplate`

不然我改成`itaigi.tw``itaigi.tw/k/...`都用`prodTemplate`
這樣`npm start`就可以都用`html/index.html`

**Comment by sih4sing5hong5** [comment]
好喲，因為`itaigi.tw`都要指向`github.io`，所以只能讓他獨立去`prodTemplate`了

**Comment by hankkk** [comment]
#260 
production server統一用prodTemplate輸出html
develop直接用index.html輸出html
