### ISSUE TITLE
我很會 沒縮圖

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#256]
https://g0v-tw.slack.com/archives/itaigi/p1475834097000300

這馬干焦做`怎樣講`，網址是`/k/:Su`
https://github.com/g0v/itaigi/blob/master/prodServer.js#L17-L20
`我很會`的網址是`/t/:Su`

看啥人會當來做，才看欲按怎deploy

**Comment by hankkk** [comment]
`我很會`若是欲加，我可以來做

**Comment by hankkk** [comment]
#258 有解
