### ISSUE TITLE
不輸入查詢瀏覽新詞

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#259]
使用者反映希望可以看到近期網友貢獻的詞，包括自己求過講法的詞，不一定主動要查甚麼，而是想要多看多學。我覺得這是個滿重要的功能，對很多初階學習者來說他主要是看而不是查，目前想到以下做法：

1.首頁「熱門詞」改為最近貢獻的10個詞，每天遞補
2.跟「主題詞條 #125 」「寶島可夢做一頁 #210 」一樣另外弄一頁

我傾向1.，不知大家覺得怎樣
首頁的那個CC笑話看久了也有點冷場，或許可以直接放新貢獻的詞多放幾個

**Comment by sih4sing5hong5** [comment]
放 `1` 呀 +1
現在的issue要一段時間消化

**Comment by hankkk** [comment]
`1` +1

**Comment by aweimeow** [comment]
一號參賽者一票～～～～！
不過最近我事情跟山一樣高 XD 需要時間慢慢做

**Comment by sih4sing5hong5** [comment]
著呀，是欲佇首頁下

A. 這馬`烏底白字`的`熱門詞`
B. 直接共這10个詞的`臺語卡片`顯示出來

我想應該是`B`較好吧？

**Comment by hankkk** [comment]
`B` +1
直接顯示效果比較好

**Comment by liz462** [comment]
直接顯示台語卡片會當顯示的詞較少，使用者嘛較無參與感？
而且網站的邏輯是華語→台語，干焦遮是台語→華語(小字)，按呢敢好？

若是這馬的烏底白字變做10个甚至20个，予使用者去點，按呢咧？嘛會當分兩區，第一種是「本月推薦詞」，第二種是「最新貢獻詞」，各10个？

**Comment by sih4sing5hong5** [comment]
我雄雄想著
咱攏是半暝共正規化結果更新

按呢一擺更新幾仔十个，才揀10个出來？
所以有的人貢獻的詞可能袂出現喲
因為數量傷過濟矣

**Comment by liz462** [comment]
定一个固定出現的數量，看版面按怎
下面提供button，揤落去，出現紲落來的20个，按呢？

**Comment by aweimeow** [comment]
現在喊 `B` +1 會不會太晚 XD
@liz462 說的 ++，覺得如果使用者有興趣的話可以再點一下載入更多

**Comment by sih4sing5hong5** [comment]
後端更新上去了
api在http://docs.tai5uan5gian5gi2phing5thai5.apiary.io/#reference/0/0 的`揣上新貢獻的外語請教條`

**Comment by sih4sing5hong5** [comment]
@alexpasta 頂禮拜做好矣
