### ISSUE TITLE
聽不到聲音

### ISSUE THREAD

**Issue by yfliao** [g0v/itaigi#263]
查詢沒問題，但完全沒有聲音。瀏覽器需要裝任何插件嗎？

**Comment by sih4sing5hong5** [comment]
@yfliao `小屁孩`六個詞都沒有聲音嗎？

**Comment by sih4sing5hong5** [comment]
mac的safari無法度合成`猴死囡仔`
mac的chrome會使合成
教典的音攏正常

**Comment by sih4sing5hong5** [comment]
@hankkk 這我試袂出來，你有閒才來鬥看一下 XDD

**Comment by sih4sing5hong5** [comment]
http://stackoverflow.com/questions/12804028/safari-with-audio-tag-not-working

**Comment by sih4sing5hong5** [comment]
應該不是onclick 問題，因為我共`src`換做萌典的就正常
可能是`wav`抑是後端回傳的物件的關係

**Comment by sih4sing5hong5** [comment]
可能是後端欠：`byte range` http://stackoverflow.com/questions/716680/difference-between-content-range-and-range-headers

**Comment by sih4sing5hong5** [comment]
http://stackoverflow.com/questions/14324250/byte-ranges-in-django

**Comment by sih4sing5hong5** [comment]
確實是`range`的關係
用https://github.com/wearespindle/django-ranged-fileresponse 就會用得矣
```
 68     def 音檔包做回應(self,request, 音檔):                                   
 69         回應 = RangedFileResponse(request,io.BytesIO(音檔), content_type='au    dio/wav')                                                                   
 70 
 71         回應['Content-Disposition'] = 'filename="taiwanese.wav"'
 72         return 回應
```

**Comment by sih4sing5hong5** [comment]
http://stackoverflow.com/questions/14324250/byte-ranges-in-django/35928017#35928017
