### ISSUE TITLE
SSL過期

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#269]
@aweimeow 咱是毋是愛用較久的？
![2016-11-09 10 13 49](https://cloud.githubusercontent.com/assets/5996555/20124945/4d5736d6-a665-11e6-9589-8973bde2429b.png)
我先改`http`

**Comment by aweimeow** [comment]
QQ 因為這個是免費的，所以每三個月就要請一次
他好像沒有寄提醒信到我的信箱，所以我沒有去 renew

**Comment by sih4sing5hong5** [comment]
如果袂傷過貴，咱來買較久的好無？

咱的工錢應該有價值

有三臺主機需要SSL

**Comment by aweimeow** [comment]
好阿 XD 或者就是直接轉域名到 Gandi（？）
我之前有 Gandi 的優惠卷，只要把域名轉到他們那邊，就免費送一年的 SSL

**Comment by sih4sing5hong5** [comment]
好呀，三个SSL，一年1365會當接受
https://www.gandi.net/ssl/standard#multi


會當請 @thewayiam 共 `voice.itaigi.tw`指到 `128.199.254.227` 無？

**Comment by thewayiam** [comment]
Done!

**Comment by liz462** [comment]
我嘛欲鬥出錢

**Comment by sih4sing5hong5** [comment]
有人建議寫script，用免錢的自動更新就好

**Comment by sih4sing5hong5** [comment]
1. 寫好`nginx`的`server_name`
2. [安裝](http://letsencrypt.readthedocs.io/en/latest/contributing.html#running-a-local-copy-of-the-client)
3. [certbot --nginx](http://letsencrypt.readthedocs.io/en/latest/using.html#nginx)
4. 定期renew
  * `crontab`
  * `screen`配`watch -n 1800 certbot --nginx renew`

**Comment by sih4sing5hong5** [comment]
請逐家來試用SSL的
https://itaigi.tw/k/%E9%AB%98%E8%B7%9F%E9%9E%8B
試一禮拜攏無問題，咱就會使佇`itaigi.tw`設定，共逐家攏轉去https

**Comment by aweimeow** [comment]
還是說我來把他寫進機器的 crontab 裡面？
我記得 letsencrypt 是每三個月需要 renew 一次，
時間設定 43200 sec 會不會太頻繁 XD

**Comment by sih4sing5hong5** [comment]
https://community.letsencrypt.org/t/help-us-test-renewal-with-letsencrypt-renew/10562
```
Q. Why does letsencrypt renew only renew some certificates?
A. letsencrypt renew has a notion of when certificates are due for renewal, currently 30 days before their expiry. We will soon document ways of changing this. Only certificates that are due for renewal get renewed, unless you specify letsencrypt renew --renew-by-default, which attempts to renewal all certificates, regardless of how old they are.
```
逐工檢查無要緊，橫直賰30工才會更新

**Comment by sih4sing5hong5** [comment]
前端嘛轉SSL矣
