### ISSUE TITLE
導覽的先後

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#276]
#211 了

* 怎樣講
* 我很會
* 名人堂
* 好工具
* 抱去摸

**Comment by aweimeow** [comment]
看不太懂 QQ 是要教使用者怎麼使用的先後順序嗎

**Comment by sih4sing5hong5** [comment]
昨昏臨時拍的

咱有五頁
佗一頁應該下佇導覽上倒爿
佗一頁下佇中央

我是感覺
`怎樣講`、`我很會`、`名人堂`是itaigi詞條相關的
這三个應該下做伙

另外兩个佗一个下較頭前

**Comment by liz462** [comment]
抱去摸是專題，照講未來會有閣較濟專題（希望啦），所以應該會閣修改

**Comment by sih4sing5hong5** [comment]
以後專題較濟，才閣講
