### ISSUE TITLE
予google會當對詞條揣著網站

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#282]
加sitemap

因為這馬揣詞條攏揣無：
![2016-11-28 10 00 56](https://cloud.githubusercontent.com/assets/5996555/20654162/92d0c7fe-b551-11e6-9a66-4401db214aa0.png)

**Comment by aweimeow** [comment]
讚讚

**Comment by sih4sing5hong5** [comment]
https://www.google.com/webmasters

**Comment by hankkk** [comment]
![image](https://cloud.githubusercontent.com/assets/8756959/22616686/cfe26974-eaec-11e6-9e3c-744cf5cb941c.png)
現在找得到了？

**Comment by sih4sing5hong5** [comment]
所以google 有空也是會去render 哦！？

那這个issue就免做矣
