### ISSUE TITLE
燒燙燙新詞 載入中愛顯示

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#285]
雄雄跳出來足奇怪
建議：
http://semantic-ui.com/elements/loader.html

**Comment by s890081tonyhsu** [comment]
路過來幫忙，先附上半成品截圖，如果有細項要確定請告訴我

![image](https://cloud.githubusercontent.com/assets/3825000/20783722/a98ac860-b7d0-11e6-9567-92ac65de46c3.png)


簡單來說就是我會先輸出這畫面，之後再把「燒燙燙新詞」的內容全部輸出

遇到的疑點整理如下：

1. 如果要有這效果，需要在CSS設定最小高度，我測試是設定最小高度150px(min-height: 150px;寫在jsx內)
2. 「燒燙燙新詞」、「顯示多/少一點」這兩個預設要顯示嗎，我測試是沒有讓他們顯示(display: none;寫在jsx內)
3. 至於CSS相關的我在想要直接寫到jsx還是css，如果是CSS的話請告訴我該怎處理

**Comment by sih4sing5hong5** [comment]
1. className+CSS ? 
2. 彼時陣是簡單設計，你若感覺提掉較順眼，就提掉
3. css好做就css，歹做就jsx，後壁的人好維護就好

**Comment by sih4sing5hong5** [comment]
幫你加權限矣
