### ISSUE TITLE
燒燙燙新詞的多顯示一點不見了

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#287]
燒燙燙新詞的多顯示一點不見了

**Comment by sih4sing5hong5** [comment]
https://github.com/g0v/itaigi/issues/285#issuecomment-264088251 提掉的
若有需要才閣加轉去

**Comment by s890081tonyhsu** [comment]
照理來說應該是會出現(我沒有刪除納功能)，我再去看一下

**Comment by s890081tonyhsu** [comment]
![image](https://cloud.githubusercontent.com/assets/3825000/20999293/8a356eba-bd4e-11e6-81be-51d7a8691323.png)

輸出錯東西了，對不起我的錯...

**Comment by aweimeow** [comment]
XD

**Comment by sih4sing5hong5** [comment]
@s890081tonyhsu 無要緊啦，我嘛無認真看就merge
其實做就merge入去
橫直逐家一息仔就會揣著問題 XD
