### ISSUE TITLE
首頁圖片不見

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#288]
logo和底下的圖片都不見

**Comment by s890081tonyhsu** [comment]
logo是我建置的時候不知為何不見的，所以可能要麻煩其他人再建置一次

**Comment by thewayiam** [comment]
@s890081tonyhsu: 你上一次deploy的時候logo圖檔名有重編https://github.com/g0v/itaigi/commit/12b79634f4c41a920ccd7fefae70533711078477
121c4ed080e9127a72d31ae85d1458fc.svg → eccf2e3b36a6668cdc699fa9c71a5b05.svg
我是重新
```
npm i
npm run deploy
```
就好了，不知道為什麼 build 會不一樣

**Comment by s890081tonyhsu** [comment]
這點我也很好奇，該不會是nodejs, npm版本號不一樣吧...(我看到檔名又變回來了)

OS: Ubuntu based on vagrant(ubuntu/trusty32 20160818.0.0)
nvm version: 0.32.1
node version: v6.9.1
npm version: v3.10.8

我強烈覺得我的編譯環境一定有差別，所以在此確認一下

**Comment by thewayiam** [comment]
npm: 3.9.5
node: v6.2.2
我沒有裝 nvm 
還蠻奇怪的，可以在測試機測試看看 https://github.com/g0v/itaigi#佈署試驗機
查查看 node_modules 裡 url-loader 的版本看看

**Comment by sih4sing5hong5** [comment]
@hankkk 我這馬共 `gh-page`→`itaigi.tw`的`CNAME`提掉矣
`itaigi.tw`彼爿方便全部轉予`gh-page`無？

感覺愛佇遮改redirect？
https://github.com/g0v/itaigi/blob/master/prodServer.js#L32-L38

**Comment by thewayiam** [comment]
當時把 
itaigi.tw/eccf2e3b36a6668cdc699fa9c71a5b05.svg
g0v.github.io/itaigi/eccf2e3b36a6668cdc699fa9c71a5b05.svg
的確就有檔案，給你們參考一下

**Comment by sih4sing5hong5** [comment]
@thewayiam 這馬 `itaigi.tw`為著FB的SEO，所以是另外一台主機
負責做`index.html`出來
賰的js, css仝款掠github.io
