### ISSUE TITLE
其他建議先暫時提掉

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#294]
因為後端的介面有改，佇 #279 提掉

1. #279 merge了
2. 後端更新
3. 前端閣一个PR補`其他建議`

@aweimeow 才麻煩你，等 #279 merge了，先更新後端

**Comment by aweimeow** [comment]
等 #279 被 Merge 後才更新後端？
還是現在先更新後端，等待 #279 Merge 後再更新一次呢？

**Comment by sih4sing5hong5** [comment]
先 #279 因為這馬的前端需要看`其他建議`
#279 就會共`其他建議`先提掉
merge了，才會當更新後端

**Comment by sih4sing5hong5** [comment]
我紲落來三四工應該攏無閒
@aweimeow 若是過一兩工， #279 逐家攏無意見，你就先merge吧 XDD

**Comment by aweimeow** [comment]
好喔！
