### ISSUE TITLE
改良的登入作法

### ISSUE THREAD

**Issue by pm5** [g0v/itaigi#31]
* 後端多一個「有登入／沒登入」的 API
* 載入時就會查有登入沒登入
* 沒登入的介面，按鈕會是「登入 & 送出」
* 講法的資料存在 localStorage
* 登入以後 next 跳回原本的網頁，並且檢查 localStorage 有沒有要送的資料，送出然後清掉 localStorage

**Comment by sih4sing5hong5** [comment]
`django-allauth`不准`redirect`到無仝domain，所以愛寫死佇`settings.py`的`LOGIN_REDIRECT_URL`

**Comment by sih4sing5hong5** [comment]
佮後端配合的，攏佇 2ce34e57aa28eca3d6386bbcd6cb3d3171099f4f 做好矣
這馬後端的導向到`//itaigi.tw/` 
賰 lcoalStorage 的部份

**Comment by pm5** [comment]
改了的差不多了。不過上次做的登入好像要再修理一下。
