### ISSUE TITLE
更新package 版本

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#327]

**Comment by sih4sing5hong5** [comment]
#332 做了，閣有`transmit`佮`webpack`猶未改

**Comment by sih4sing5hong5** [comment]
@aweimeow @hankkk @thewayiam @s890081tonyhsu @a8568730 
專案有更新了，開發時記得重走`npm i`

**Comment by a8568730** [comment]
transmit更新到3.2.0囉
