### ISSUE TITLE
建議送出後，excel的漢字會出錯

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#33]
前端輸入漢字和台羅，google sheet在漢字那一欄，會出現漢字欄的第一個字和台羅欄的第二個字。
例如：
輸入  `死侍``sú-sū` 在sheet會出現  `死su7`

**Comment by liz462** [comment]
在「我就是沒有人我來講」，輸入之後，點選送出：
1.會跳到FB登入要求再打一次密碼。　
2.輸入密碼之後，剛剛打的內容已被清除。
3.再打一次按下送出，確實送到後端，但前端沒有提示。

能否做成像hackpad一樣，開始輸入時按下第一個按鍵，就跳出提醒，要求使用者登入FB或google，若當時使用者已登入FB，就可以不要再輸入一次密碼，直接登入。
按下送出時，要跳出提醒：「我們會在檢查和字拼音後釋出您的建議」

另外，或許有人不願意具名提供講法，是不是也要允許不具名提供？

**Comment by liz462** [comment]
沒有解決!!!!!

**Comment by liz462** [comment]
補充，登入的部分解決了，但前面：輸入 死侍sú-sū 在sheet會出現 死su7

尚未解決

**Comment by sih4sing5hong5** [comment]
主要的issue是 #29

**Comment by sih4sing5hong5** [comment]
閣有`點攄螢幕`/`tiám-lu-îng-bōo`

**Comment by sih4sing5hong5** [comment]
這馬`音標`袂佮`漢字`濫做伙

這馬是`音標`無去矣

**Comment by sih4sing5hong5** [comment]
佇 <https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/pull/62> 做好矣
