### ISSUE TITLE
Safari 播放問題

### ISSUE THREAD

**Issue by eric0324** [g0v/itaigi#338]
[Imgur](http://i.imgur.com/ymaci5Y.png)

右上播放功能，在 Safari 下會無法正常播放。

**Comment by sih4sing5hong5** [comment]
多謝回報，
這可能是我前幾工加nginx的cache設定造成無`content-range`
隨就予人發覺 XD

我這幾工揣時間修

**Comment by sih4sing5hong5** [comment]
確實是`nginx cache`影響著

http://stackoverflow.com/a/22831295 無效

看 http://stackoverflow.com/questions/21888138/safari-strange-behaviour-with-range-header 
可能有content-range就愛回傳206，予nginx 莫cache

**Comment by sih4sing5hong5** [comment]
筆記
https://www.nginx.com/blog/smart-efficient-byte-range-caching-nginx/
`time curl 'https://voice.itaigi.tw/%E6%96%87%E6%9C%AC%E7%9B%B4%E6%8E%A5%E5%90%88%E6%88%90?%E6%9F%A5%E8%A9%A2%E8%85%94%E5%8F%A3=%E9%96%A9%E5%8D%97%E8%AA%9E&%E6%9F%A5%E8%A9%A2%E8%AA%9E%E5%8F%A5=ti%C4%81n-tsu-%C3%A1' -D aa -r 1-5 > /dev/null ; cat aa`

**Comment by sih4sing5hong5** [comment]
連`cache_bypass`攏會變200，可能是cache實作的問題
愛自django彼爿處理矣

**Comment by sih4sing5hong5** [comment]
揣著原因矣
https://github.com/wearespindle/django-ranged-fileresponse/pull/2

**Comment by ellenpost** [comment]
粉絲回報 ipad air 2 無法發音 頭水的例句

**Comment by sih4sing5hong5** [comment]
@ellenpost 若你試無問題，就close
