### ISSUE TITLE
討論區/FB討論

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#339]
使用者建議是否可以把在FB的討論，自動連結到iTaigi。

到目前為止，我們的討論區功能使用率不高，有人留言之後，被下一個人看到的機率滿低的，可能大家也比較習慣在FB討論。而FB因為粉專會發一些詞，多少就會引起一些討論，但比較不會想要去iTaigi的討論區留言。

除了把兩邊連起來之外，也可以考慮其他方法讓討論比較容易被看到、繼續討論。

**Comment by sih4sing5hong5** [comment]
確實佇仝一爿討論就好

若按呢，欲按怎連結，逐頁辭條愛連去佗位？

**Comment by liz462** [comment]
FB無可能有全部，iTaigi才有，所以照講是愛佇iTaigi討論區這爿。
毋過這敢做會到？我嘛那想別項方法。

**Comment by sih4sing5hong5** [comment]
可能就是佇iTaigi討論區討論，
予伊會自動貼去FB粉專

**Comment by sih4sing5hong5** [comment]
http://stackoverflow.com/questions/11580579/link-or-connect-facebook-comments-plugin-to-comments-on-fan-page-wall-posts

**Comment by sih4sing5hong5** [comment]
佇 #408 討論
