### ISSUE TITLE
點首頁圖片要能連回FB

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#34]
首頁自動抓FB圖的地方，點圖片要能連回FB粉專
之後的youtube也一樣

**Comment by sih4sing5hong5** [comment]
你是說`Facebook Image (Timeline Photos)`這個？

**Comment by liz462** [comment]
對，點了Facebook Image (Timeline Photos)底下的圖，要連結到：https://www.facebook.com/ukauitaigi/photos/a.1661030874179270.1073741826.1661026360846388/1670790819869942/?type=3&theater

**Comment by sih4sing5hong5** [comment]
用`Link`元件，會當參考`GuanKiann/ToLam/ToLam.jsx`的語法`<Link to='/k' params={{ k: '' }}> 怎樣講</Link>`
愛改佇`FBTest/FBTest.jsx`

**Comment by mhshih** [comment]
不太懂這個功能是要連回原PO圖嗎
連回FB粉專首頁就好吧

**Comment by liz462** [comment]
連回原PO圖可以嗎？可能有人會想要copy文字

**Comment by mhshih** [comment]
嗯嗯 可能要研究一下當初如何抓FB圖片了

**Comment by mhshih** [comment]
記錄一下台語松問 @mxgit1090 連FB Graph API的技術文件厚:
1. [Facebook SDK for JavaScript](https://developers.facebook.com/docs/javascript/quickstart/v2.5)
2. [Facebook Login](https://developers.facebook.com/docs/javascript/examples#login)
3. GET graph.facebook.com /v2.5/ukauitaigi/feed
4. [Graph API Reference: page/feed](https://developers.facebook.com/docs/graph-api/reference/v2.5/page/feed)
5. [Graph API Explorer](https://developers.facebook.com/tools/explorer)

**Comment by mhshih** [comment]
```
FB.getLoginStatus(function(response) {
  if (response.status === 'connected') {
    FB.api('/ukauitaigi/feed', function(response) {
      console.log(response.data.id);
    });
  }
});
```

**Comment by mxgit1090** [comment]
當時我是用 FQL 來接的，一直想改成最新的 graph API
App 調權限的地方需要研究看看

**Comment by sih4sing5hong5** [comment]
前幾工萌典松的時陣 @thewayiam 說可能要使用者登入fb才看得到
因為那天趕上線，
所以現在暫時先把圖片網址寫死 #116
