### ISSUE TITLE
臉書上貼文的字無法顯示

### ISSUE THREAD

**Issue by ellenpost** [g0v/itaigi#392]
掠

Browser: Chorme Version 56.0.2924.87
OS Win10 pro 64bit

![default](https://cloud.githubusercontent.com/assets/7560231/24319810/dd13cbba-1161-11e7-9096-6b571301673e.png)

**Comment by sih4sing5hong5** [comment]
https://www.facebook.com/ukauitaigi/posts/1861068664175489

**Comment by sih4sing5hong5** [comment]
```
>>> a='掠͘'   
>>> ord(a[0])
25504
>>> ord(a[1])
856
```

**Comment by sih4sing5hong5** [comment]
可能是貼的時候，選著聲調符號
