### ISSUE TITLE
例句複製

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#396]
https://g0v-tw.slack.com/archives/C0N9DK6JU/p1489500152802637

解法：
AU:
```

<show>abc</show>
<copy>ABC</copy>


after before
visibility size 0

copy fony-size 0


user-select:none

unselectable
```

**Comment by KevinHu2014** [comment]
![2017-03-25 6 26 46](https://cloud.githubusercontent.com/assets/7204070/24321474/ada0b0c4-1188-11e7-9121-a3b70ff3327d.png)

在例句的顯示看似正常
但在複製後的文字會變成：

> 兩tsiah隻gû牛teh咧sio-tak相觸.

**Comment by a8568730** [comment]
MDN-[copy event](https://developer.mozilla.org/en-US/docs/Web/Events/copy)
DEMO: https://jsfiddle.net/sidk/e31nuk49/
