### ISSUE TITLE
手機版的例句 跑版

### ISSUE THREAD

**Issue by KevinHu2014** [g0v/itaigi#401]
![2017-03-27 6 58 06](https://cloud.githubusercontent.com/assets/7204070/24353260/647f1230-131f-11e7-9816-b3ea25029345.png)

**Comment by a8568730** [comment]
修改行距後的華語
![17778968_1501801446520f905_1059332140_o](https://cloud.githubusercontent.com/assets/6355592/24695570/dcf90bb2-1a18-11e7-9009-f6ddc346dea1.png)
