### ISSUE TITLE
首頁 有錯誤

### ISSUE THREAD

**Issue by Misui** [g0v/itaigi#409]
<img width="1144" alt="screen shot 2017-05-06 at 4 01 04 pm" src="https://cloud.githubusercontent.com/assets/8425533/25770956/d815a784-3275-11e7-8665-8ed2152ef0f3.png">

**Comment by Misui** [comment]
我開到 localhost , sorry

**Comment by sih4sing5hong5** [comment]
@Misui 這是因為瀏覽器cache的關係，伊連header攏cache，所以比對會錯誤

**Comment by Misui** [comment]
@sih4sing5hong5  宛來魯觸，甘蝦哩!!!!!
