### ISSUE TITLE
台語姓名產生器/稱號產生器/造句產生器

### ISSUE THREAD

**Issue by fhj17** [g0v/itaigi#415]
目前已有台語姓名產生器的坑挖好了，往後延伸可以變成台語稱號產生器。
隨機拉霸的「形容詞」+「姓名」，例如：妖嬌的陳美美、吃人夠夠的張大華、中二病的林義氣。
之後可以將產生結果與語音合成的結果分享到社群平台。

造句團康遊戲通常是有「人」、「事」、「時」、「地」、「物」。
例：王小明、吃、跨年前五秒、廁所、泡麵。

依語法安排可能會是「人」「時」在「地」「事」「物」的順序。
得到結果➡️「王小明跨年前五秒在廁所吃泡麵。」
這樣也許是可以訓練大家造句的小工具！

**Comment by sih4sing5hong5** [comment]
@glll4678 hackpad欲收攤矣
你共hackpad的資料貼來遮抑是hackmd？

**Comment by sih4sing5hong5** [comment]
## 起因

足濟人佇iTaigi頂懸問人名欲按怎講，毋過，iTaigi這馬干焦會收公眾人物的名爾爾。
所以，就想講，會使做這个功能，予逐家攏會使知影家己的名欲按怎用台語講，嘛會使透過這个功能來推廣羅馬字。

    很多人在iTaigi上面問人名怎麼說，不過，iTaigi現在只會收公眾人物的名字而已。

    所以，就想說，可以做這個功能，讓大家都可以知道自己的名字要怎麼用台語說，也可以透過這個功能來推廣羅馬字。

```

**Comment by aweimeow** [comment]
好喜歡這個想法喔 XD 這好棒

**Comment by sih4sing5hong5** [comment]
https://github.com/g0v/itaigi-mia-senn

**Comment by rschiang** [comment]
＊雖然 g0v/itaigi-mia-senn 好像沒有什麼在更新了，但教育部[講我的名](https://miasenn.moe.edu.tw/)網站有上線囉。

> 為配合《國家語言發展法》通過，及外交部《護照條例施行細則》第14條規定：「外文別名應有姓氏，並應與外文姓名之姓氏一致，或依申請人對其中文姓氏之母語讀音音譯為英文字母。」考量護照姓名可改以「國家語言讀音」逐字音譯，教育部於108年起規劃「姓名查詢功能工作計畫」，並提供音檔， 供各界參考使用。
