### ISSUE TITLE
求講法實作

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#42]
揤落了
愛共人問的`華語`下去`求講法`頁

路人會當去去`求講法`頁
拉霸
看有佗一個`華語`詞無人講
伊就會使提供一個`臺語`詞/音檔

**Comment by liz462** [comment]
後端正規劃工作表應該要有兩張：
一、目前的iTaigi正規化工作表→見#issue38
二、本項，求講法→這張表中只有華語詞，前端呈現方式就是上面說的拉霸。

**Comment by liz462** [comment]
使用者點了求講法之後，畫面彈出視窗「台語阿肥收到了」(還沒做)，停在原畫面。
這個華語詞進入後端(還沒做)
前端視呈現這樣：
**https://moqups.com/liz462/IMYHBVi5/p:a464d2759**
先用下拉式選單，未來再做拉霸
