### ISSUE TITLE
branch欲merge入master的時陣，自動deploy

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#426]
https://docs.travis-ci.com/user/deployment/pages/

我的範例佮指令（欠fqdn）：https://github.com/i3thuan5/i3thuan5/pull/27

@aweimeow 敢有興趣做看覓，順紲寫blog XDD

**Comment by aweimeow** [comment]
好呀 XD

**Comment by aweimeow** [comment]
完工！

<img width="1012" alt="2017-07-21 12 53 43" src="https://user-images.githubusercontent.com/5120010/28449583-b6ce9c78-6e13-11e7-8636-de85141d37ca.png">
