### ISSUE TITLE
藏起不需要的詞條版面障礙

### ISSUE THREAD

**Issue by liz462** [g0v/itaigi#430]
161946  長度太長導致版面橫向擴展，超出版面，按不到隱藏
且不知道是不是因為資料太多，速度越來越慢的感覺，能不能把隱藏的那些真的刪除？之後隱藏就直接刪除可以嗎？

**Comment by glll4678** [comment]
吃了1.75G的記憶體...
![default](https://user-images.githubusercontent.com/6016585/28874217-7a5b0416-77c3-11e7-8005-d58ba7e70a12.PNG)

**Comment by sih4sing5hong5** [comment]
我後禮拜揣時間出來，先處理這个問題

**Comment by sih4sing5hong5** [comment]
@glll4678 你這兩工仔敢有閒？
我教你改

https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/master/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E5%B9%B3%E8%87%BA/%E5%A4%96%E8%AA%9E%E8%AB%8B%E6%95%99%E6%A2%9D.py#L70-L80
限制莫全部輸出
加上`[:300]` 限制頭前300个
改好我教你更新主機

[python語法](https://stackoverflow.com/a/45370737/3640653)
看[ssh](http://www.linuxproblem.org/art_9.html)了後，共pub傳fb予我，才會當登入主機

**Comment by sih4sing5hong5** [comment]
我先限制300个，以後才閣改較好勢
