### ISSUE TITLE
Travis ci ê slack thong-ti

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#431]
https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications

@Aweimeow 欲耍看莫無？

**Comment by aweimeow** [comment]
好 ~

**Comment by aweimeow** [comment]
@sih4sing5hong5 

g0v Slack Team 已經到 Free Plan 最大 Integration application 數量了，
所以沒辦法再新增了 😢 

<img width="984" alt="2017-07-25 12 24 17" src="https://user-images.githubusercontent.com/5120010/28555713-372aeebc-7134-11e7-895c-fa0717d7dce0.png">

**Comment by aweimeow** [comment]
還是這能夠去 #general 喊看看，
看有沒有哪個是沒有使用到的，看有三四個都是只有一個 Configuration

**Comment by sih4sing5hong5** [comment]
M̄-bián--ah
