### ISSUE TITLE
disqus廣告誠濟

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#434]
面頂下跤攏有，有兩區
![2017-08-22 10 20 37](https://user-images.githubusercontent.com/5996555/29570161-358123e6-8788-11e7-9769-f99653c020cb.png)

**Comment by aweimeow** [comment]
我把 adblock 關掉沒看到這些廣告耶 XD

**Comment by s890081tonyhsu** [comment]
![default](https://user-images.githubusercontent.com/3825000/31137885-1ec7cf50-a89f-11e7-8dba-24e4e5870ca8.png)
在網站的Settings頁面中，左方有一個叫Ads的功能。
我的blog設定就如上圖所示，不知道itaigi的長怎樣？

**Comment by thewayiam** [comment]
一定要選一個位置和一種廣告類型，先選了最下面的位置和最不顯眼的
![image](https://user-images.githubusercontent.com/4479861/31138408-f31806e8-a8a0-11e7-991f-ec6a60bfa871.png)

**Comment by leo424y** [comment]
目前留言功能已用 fb-comment 替代
