### ISSUE TITLE
覺得三張卡片沒有與搜尋列對齊很想幫它對齊，請問要如何寫呢？

### ISSUE THREAD

**Issue by leo424y** [g0v/itaigi#442]
<img width="991" alt="screen shot 2017-11-19 at 3 18 32 pm" src="https://user-images.githubusercontent.com/1384394/32988336-a829c34c-ccc7-11e7-8612-86bae8abd2cf.png">

**Comment by sih4sing5hong5** [comment]
這較困難，我無確定做會到無，你會當試看覓

先看下跤三張圖，面頂攏有對齊線
是`guaGi`無佇中央，所以是`guaGi`的問題，程式佇`src/GuanKiann/GuaGi`
`GuaGi`用著[semantic-ui的Card](https://semantic-ui.com/views/card.html)，這你就愛查有法度解決無


![2017-11-20 12-17-46](https://user-images.githubusercontent.com/5996555/33002140-203b5424-cded-11e7-8d26-ac8eedd47ef6.png)
![2017-11-20 12-18-02](https://user-images.githubusercontent.com/5996555/33002141-206447e4-cded-11e7-8c78-1206e8800826.png)
![2017-11-20 12-18-27](https://user-images.githubusercontent.com/5996555/33002142-208c4a64-cded-11e7-821f-c62bcba26614.png)

**Comment by leo424y** [comment]
太好了，謝謝丞宏給的線索，我再來多試試
