### ISSUE TITLE
search bar在 iphone跑版

### ISSUE THREAD

**Issue by leo424y** [g0v/itaigi#462]
但在開發環境不會... 
控制它的css是 App.css >   .fixbar
https://github.com/g0v/itaigi/blob/master/src/App/App.css
![received_10211677886524693](https://user-images.githubusercontent.com/1384394/35494736-a1437cae-04f7-11e8-8b8f-d1195a7cac05.jpeg)

**Comment by sih4sing5hong5** [comment]
Tsit-má正常
