### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jhs-tw** [g0v/itaigi#528]
![PartialScreenshot_20200924-112200](https://user-images.githubusercontent.com/42627483/94097120-70b97180-fe58-11ea-840c-2b7cbfd0f173.png)

**Comment by jhs-tw** [comment]
這久恢復正常矣

**Comment by justinrleung** [comment]
這馬閣來矣

**Comment by sih4sing5hong5** [comment]
多謝回報，huān-sè是自動重開造成--ê，後kái 改版會做伙處理

**Comment by sih4sing5hong5** [comment]
#534 修--ah
