### ISSUE TITLE
按下「求講法」要顯示媠媠的「送出成功」

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#57]

**Comment by sih4sing5hong5** [comment]
#58 做了後，生按呢
文案愛想一下喲～～

![default](https://cloud.githubusercontent.com/assets/5996555/16398346/4589a8b2-3cfc-11e6-87e2-86f02653b11f.png)

**Comment by liz462** [comment]
收到！在「我很會」等待講法中......

這樣好嗎？

**Comment by sih4sing5hong5** [comment]
好喲，看欲閣加圖抑是按呢

這會當佇人濟的時陣討論
