### ISSUE TITLE
「我來講」改成可以登入也可以不登入

### ISSUE THREAD

**Issue by pm5** [g0v/itaigi#59]
經過[討論](https://g0v.hackpad.com/coding-iTaigi-6ARoXv4DSQo#:h=%E7%AC%AC5%E6%AC%A1%E5%8F%B0%E8%AA%9E%E6%9D%BE)決定，對於提供講法的可以登入也可以不登入：

* 登入的話，就記下提供的人的資料
* 沒登入的話，就匿名提供，提詞不欲人知

**Comment by sih4sing5hong5** [comment]
如果還沒登入，應該有兩個按鈕給他按？
