### ISSUE TITLE
Safari, IE11 殕殕殕

### ISSUE THREAD

**Issue by glll4678** [g0v/itaigi#66]
![2016-06-13 16 08 46](https://cloud.githubusercontent.com/assets/6016585/16000808/234ffc0a-3181-11e6-91c4-e4939b7d9481.png)

Chomre, Edge, Firefox, Oprea 正常

**Comment by sih4sing5hong5** [comment]
現在什麼系統只有IE 11，沒有IE Edge呀？

**Comment by thewayiam** [comment]
js normalize [Safari & IE 不支援...](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize)

用 [unorm](https://github.com/walling/unorm) 取代後首頁可以顯示了，但詞條顯示不出來，晚點#107 close 後附上 commit

**Comment by sih4sing5hong5** [comment]
safari #143 可以正常了
我們有需要修ie嗎？感覺無底洞 XDD

**Comment by liz462** [comment]
ie先不要管他好惹XD
與其修ie，不如先接語音合成!!!

**Comment by sih4sing5hong5** [comment]
那這件代誌就好矣
共伊關關掉，issue -1
