### ISSUE TITLE
安裝問題

### ISSUE THREAD

**Issue by thewayiam** [g0v/itaigi#67]
environment: ubuntu 14.04 64bit

`npm i` with error message:
```
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary
```
fixed by `apt-get install nodejs-legacy`

then `npm i` succeed, then `npm start` with error message:
```
 ERROR in Cannot find module 'babel-runtime/helpers/typeof'
```
fixed by `rm -rf node_modules && npm install`

If this is just cause by different environment, I would like to add remark on README and send PR.

**Comment by sih4sing5hong5** [comment]
我記得預設nodejs版本好像會太舊？
你這樣可以跑嗎？

**Comment by thewayiam** [comment]
前端可以

**Comment by sih4sing5hong5** [comment]
那就直接加到README好了

**Comment by sih4sing5hong5** [comment]
b926471bb1acfdc71f8ddc7db0a6bc363aec71fb 好像沒有加到前端的`npm`耶 XDD

**Comment by sih4sing5hong5** [comment]
@thewayiam 佇 62366ae900939fae60ad70fafe0ac44bb10df1f4 做好矣
