### ISSUE TITLE
校對不完整的處理方法

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#77]
@liz462 
若excel內底，有一逝有簽名
毋過伊干焦寫`正規漢字`，無`臺羅`，按呢欲按怎處理

**Comment by liz462** [comment]
正確臺羅愛有才會使出去。
若是正確華語無，無要緊，應該就是袂記得copy爾爾。正確漢字無，嘛無要緊，因為有可能無漢字。賰的我會佇正規化團隊說明的時交代。

**Comment by sih4sing5hong5** [comment]
閣有一個問題
若是`漢字`佮`臺羅`攏無寫，是愛當作
1. 民眾提供的講法是著的
2. 正規化團隊簽名了袂記得改`漢字`佮`臺羅`

**Comment by liz462** [comment]
應該愛當做2.
按呢按怎處理較好?若發現這款情形共簽名刣掉敢會使？抑是檢查著就緊補？

**Comment by sih4sing5hong5** [comment]
好，我共`簽名`提掉

**Comment by sih4sing5hong5** [comment]
https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/issues/107 做好矣
