### ISSUE TITLE
「按呢講好」、「按呢無好」、「討論」

### ISSUE THREAD

**Issue by pm5** [g0v/itaigi#8]
* [ ] 臉書登入
* [ ] 後端
  * [ ] 存使用者帳號
  * [ ] 存使用者按「好」、「無好」的資料
  * [ ] 用「好」、「無好」數目把講法排序
* [ ] 前端
  * [ ] 每個講法的 permalink
  * [ ] 接按鈕
  * [ ] 接臉書討論
  * [ ] 接排序列出講法

**Comment by sih4sing5hong5** [comment]
拆做 #9 佮 #10
