### ISSUE TITLE
提供講法傷慢

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#82]
因為愛連google sheet
所以速度傷慢

改良做法：
1. 後端先response，後端才隨加入去google sheet
  * message queue
    * http://stackoverflow.com/a/9496041/3640653
2. 做一個api，予正規化團隊去點，才閣匯入去google sheet

**Comment by thewayiam** [comment]
可以標註一下那些 function 要放進 message queue 嗎？
找了一下`加新詞影音` 在 src 居然沒有@@

**Comment by sih4sing5hong5** [comment]
因為 @pm5 佮 @a-tsioh 的`錄音`猶未做好（欠encoding的款？），所以我嘛無法度接
前端的`加新詞影音`就猶未用著

這馬慢的是有用著sheet的[新文本自資料庫加入sheet](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/master/臺灣言語平臺/正規化團隊模型.py#L98-L112)一個函式爾爾
`正規化文本自sheet加轉資料庫`會用crontab，所以就無需要message queue
