### ISSUE TITLE
「我很會」有人烏白試的資料愛按怎處理

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#91]
親像按呢
![default](https://cloud.githubusercontent.com/assets/5996555/16587183/f01deae0-42fb-11e6-8d8c-f455476bdb89.png)
愛佇佗位共因提掉？

**Comment by liz462** [comment]
資料是囥佇佗？共囥的所在予正規化團隊，予阮知影按怎刣，阮就來刣

**Comment by sih4sing5hong5** [comment]
資料下佇後端資料庫

若無阮另外做一頁，予恁刣？

**Comment by thewayiam** [comment]
要不要開一個欄位，由正規化團隊標明刪除，後端就定期更新&刪除
我先自首 `47984	匿名	討厭	t8	tt8` 就是我開發時候忘記不小心上傳的 Orz

**Comment by sih4sing5hong5** [comment]
變通的做法是在`sheet`不要正規化，那個辭條就不會被移回`資料庫`
久了就會被洗在上面了

現在的流程是
1. 華語只要沒有「正規化過的臺語」就會出現在「無建議的詞」
2. 臺語只要沒被「正規化過」就不會出現在「建議詞」裡
我有把他們寫在[試驗](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_phing5-tai5/blob/master/features/%E6%B1%82%E8%AC%9B%E6%B3%95%E9%96%A3%E6%9C%89%E4%BA%BA%E4%BE%86%E8%AC%9B.feature#L19)內底

**Comment by thewayiam** [comment]
可能還是有需要隱藏的需求
像目前有個防曬乳在正規畫表有兩個 http://itaigi.tw/k/%E9%98%B2%E6%9B%AC%E4%B9%B3
還是有別的比較好的做法？

**Comment by sih4sing5hong5** [comment]
嗯，看起來是愛有一个方法藏起來
若準做按呢，愛按怎做較好

無適合的華語（無臺語講法的華語，求講法產生的）
1. 做一个管理後臺處理
  * 愛管理帳號
2. 閣另外用一个sheet管理
3. 過一個月若無人提供臺語講法，就藏起來

無適合+正規化過的臺語（親像`防曬乳`有兩個仝款的臺語講法）
1. 做一个管理後臺處理
  * 愛管理帳號
2. 閣另外用一个sheet管理
3. 這馬的sheet加一個欄位
4. 予「按呢講好」「按呢講無好」去排先後，莫處理
做法1、2、3可能無好操作
因為前臺看著的，後臺閣愛去揣一擺，操作流程愛先想好

**Comment by liz462** [comment]
「要不要開一個欄位，由正規化團隊標明刪除，後端就定期更新&刪除」→贊成
不過這是**有台語講法**的部分

丞宏原本講的，猶無台語講法的詞（佇"我很會"），是欲按怎刣掉？

**Comment by sih4sing5hong5** [comment]
刣猶無台語講法的詞（佇"我很會"）的做法

1. 在`平臺項目表`加一個欄位，記錄有沒有被刪掉
2. 然後`平臺項目表.無建議講法的外語表()`在query那邊
3. 佇`介面/工作.py`開一个view，來調`1`的欄位
