### ISSUE TITLE
celery若無開，愛提醒

### ISSUE THREAD

**Issue by sih4sing5hong5** [g0v/itaigi#94]
若是
- `django`、`rabbitmq`有開，`celery`無開
  - `django`袂有錯誤，sheet袂有資料
  - `celery`後尾閣拍開，就會共進前`django`的代誌做了
- `django`、`celery`有開，`rabbitmq`無開
  - `celery`會一直`[Errno 111] Connection refused.  Trying again in 8.00 seconds...`
  - `django`用著對應的api，會`internal server error 500`

咱敢有法度按怎提醒使用者無？毋過按呢嘛小可仔複雜@@

**Comment by thewayiam** [comment]
新機器用 supervisor 控管，死掉會重啟，還要再提醒嗎？

**Comment by sih4sing5hong5** [comment]
無看著 @thewayiam 的留言

這个issue就先關掉，以後定定出問題才處理
