### ISSUE TITLE
開發用 facebook 登入顯示錯誤

### ISSUE THREAD

**Issue by thewayiam** [g0v/itaigi#98]
跟著 https://github.com/g0v/itaigi#登入管理員並且設定fb-app
登入時顯示：

![image](https://cloud.githubusercontent.com/assets/4479861/16733179/0efe3576-47b3-11e6-90f3-10cea8a44585.png)

我另外建了一個 fb app 測試，要設定如下才可登入：

![image](https://cloud.githubusercontent.com/assets/4479861/16733230/4654a622-47b3-11e6-8581-bb0877445b7a.png)

看是不是可以把 README 裡 這個開發用的 app 設定專門給 localhsot 用

**Comment by sih4sing5hong5** [comment]
意思是我們線上和開發的分兩組？

**Comment by thewayiam** [comment]
在設定 fb app 的時候，`網站網址`不設 localhost 的話，`應用程式網域`也不給設 localhost，就無法在開發機登入，可是線上的網站網址本來就該設 itaigi.tw，所以想說分開好像比較簡單，你覺得OK的話我就把我現在建好的開發用 fb app id key 更新進 README，這樣你線上的就不用動

**Comment by sih4sing5hong5** [comment]
好，就用新的到README

**Comment by thewayiam** [comment]
發現還有點問題，只有建 app 的帳號可登入，先不要關 issue

**Comment by sih4sing5hong5** [comment]
我想著矣，我嘛拄著這問題過，是pm5講的
![default](https://cloud.githubusercontent.com/assets/5996555/16909384/f943c80c-4d04-11e6-8490-042eb09dc707.png)

**Comment by thewayiam** [comment]
有開，剛剛試發現可以了，先關了
